name: Build-Debs

on:
  schedule:
    - cron: '0 21 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: save working directory in variable 'DIR'
        run: echo "DIR=$(pwd)" >> $GITHUB_ENV

      - name: setup node
        uses: actions/setup-node@v2
        with:
         node-version: '14'

      - name: clone min repo and checkout latest release
        run: |
          cd $DIR
          rm -rf min
          git clone https://github.com/minbrowser/min
          cd min
          
      - name: Build
        run: |
          LATEST=`curl -s https://api.github.com/repos/minbrowser/min/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")'`
          cd $DIR/min
          npm install
          npm run buildRaspi
          npm run buildLinuxArm64
          ls dist/app/
          
      - name: Upload
        run: |
          cd $DIR
          LATEST=`curl -s https://api.github.com/repos/minbrowser/min/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")'`
          git config user.name 'Ryan Fortner'
          git config user.email 'ryanfortner@users.noreply.github.com'
          rm -rf *.deb
          mv min/dist/app/*.deb .
          rm -rf min
          git add .
          git commit -m "update to ${LATEST}"
          git push origin main
